controller:
  replicas: 2

ingress:
  main:
    ingressClassName: "nginx"
    hosts:
      - host: ""
        paths:
          - path: /
            pathType: Prefix

resources:
  requests:
    memory: "500Mi"
    cpu: "100m"
  limits:
    memory: "2Gi"
    cpu: "2000m"
