apiVersion: v2
name: cubesigner-signer
description: A Helm chart for the DOGEOS CubeSigner Attestation Signer
type: application
version: 0.1.2
appVersion: "0.1.0"
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: DogeOS69
    email: support@dogeos.com

dependencies:
  - name: common
    repository: "oci://ghcr.io/scroll-tech/scroll-sdk/helm"
    version: 1.5.1
  - name: external-secrets-lib
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    version: 0.0.4
