---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fee-oracle-config
  labels:
    {{- include "scroll-sdk.labels" $ | nindent 4 }}
data:
  fee_oracle.toml: |
{{ .Values.feeOracleConfig | indent 4 }}
