global:
  nameOverride: &app_name dogeos-da
  fullnameOverride: *app_name

controller:
  type: statefulset
  replicas: 1
  strategy: RollingUpdate

image:
  repository: dogeos69/da
  pullPolicy: IfNotPresent
  tag: v0.0.2

service:
  main:
    enabled: false
    # ports:
    #   http:
    #     enabled: true
    #     port: 3001

defaultProbes: &default_probes
  enabled: true
  custom: true
  spec:
    httpGet:
      path: "/healthz"
      port: 8080

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

# Direct environment variables
env:
  - name: API_KEY
    value: ""
  - name: L1_CHAIN_PROXY
    value: ""
  - name: END_POINT
    value: ""
# Environment variables from ConfigMap
# envFrom:
#   - configMapRef:
#       name: dogeos-da-env

# ConfigMap for non-sensitive configuration
# configMaps:
#   env:
#     enabled: true
#     data:

# External Secrets configuration
# externalSecrets:
#   dogeos-da-secrets:
#     provider: aws
#     data:
#       - remoteRef:
#           key: dogeos/withdrawal-processor/nownodes
#           property: api-key
#         secretKey: nownodes-api-key
#       - remoteRef:
#           key: dogeos/withdrawal-processor/doge
#           property: signer-private-key
#         secretKey: doge-signer-private-key
#     refreshInterval: 2m
#     serviceAccount: external-secrets

# Resource configuration
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Persistent storage configuration
# persistence:
#   data:
#     enabled: true
#     type: pvc
#     mountPath: /data
#     accessMode: ReadWriteOnce
#     size: 1Gi

# Monitoring configuration
# serviceMonitor:
#   main:
#     enabled: true
#     labels:
#       release: scroll-sdk
#     serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
#     endpoints:
#       - port: http
#         interval: 1m
#         scrapeTimeout: 10s
#         path: /metrics
