---
apiVersion: v2
description: scroll helm charts to deploy scroll sdk for dogeos
name: scroll-sdk
version: 0.1.18-dogeos
appVersion: v0.1.0
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
keywords:
  - scroll
  - scroll-sdk
home: https://github.com/dogeos69/scroll-sdk
dependencies:
  - name: contracts
    version: 0.1.22
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: contracts.enabled
  - name: fee-oracle
    version: 0.0.7
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: gas-oracle.enabled
  - name: l2-rpc
    version: 0.1.15
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: l2-rpc.enabled
  - name: l2-sequencer
    version: 0.1.14
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: l2-sequencer.enabled
  - name: postgresql
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: 15.5.0
    condition: postgresql.enabled
  - name: rollup-relayer
    version: 0.1.12
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: rollup-relayer.enabled
  - name: scroll-common
    version: 0.1.1-dogeos
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: scroll-common.enabled
  - name: da-publisher
    version: 0.0.7
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: da-publisher.enabled
  # - name: install-cubesigner-signers
  #   repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
  #   version: 0.1.7
  - name: tso-service
    version: 0.1.4
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: tso-service.enabled
  - name: withdrawal-processor
    version: 0.1.17
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    condition: withdrawal-processor.enabled
  - name: celestia-devnet
    version: 0.1.0
    repository: "file://../celestia-devnet"
    condition: celestia-devnet.enabled
  - name: celestia-node
    version: 0.1.12
    repository: "file://../celestia-node"
    condition: celestia-node.enabled
  - name: l1-interface
    version: 0.0.18
    repository: "file://../l1-interface"
    condition: l1-interface.enabled
