---
controller:
  replicas: 1
  strategy: RollingUpdate
  type: statefulset

global:
  nameOverride: &app_name coordinator-api
  fullnameOverride: *app_name

image:
  repository: scrolltech/coordinator-api
  pullPolicy: IfNotPresent
  tag: v4.5.39

env:
  - name: HTTP_PORT
    value: 8080
  - name: METRICS_PORT
    value: 8090
  - name: RUST_LOG
    value: info
  - name: SCROLL_PROVER_ASSETS_DIR
    value: "/data/assets/"

envFrom:
  - configMapRef:
      name: coordinator-api-env

command:
  - "bash"
  - "-c"
  - "coordinator_api --config /coordinator/conf/coordinator-config.json \
    --genesis /app/genesis/genesis.json \
    --http --http.addr '0.0.0.0' --http.port ${HTTP_PORT} \
    --metrics --metrics.addr '0.0.0.0' --metrics.port ${METRICS_PORT} \
    --log.debug"

resources:
  requests:
    memory: "20Gi"
    cpu: "50m"
  limits:
    memory: "24Gi"
    cpu: "200m"

persistence:
  *app_name:
    enabled: true
    type: configMap
    mountPath: /coordinator/conf/
    name: coordinator-api-config
  download-params:
    enabled: true
    type: configMap
    mountPath: /download-params.sh
    name: coordinator-api-download-params
    defaultMode: "0777"
  genesis:
    enabled: true
    type: configMap
    mountPath: /app/genesis/
    name: genesis-config

volumeClaimTemplates:
  - name: verifier
    accessMode: "ReadWriteOnce"
    size: "100Gi"
    mountPath: "/verifier"

service:
  main:
    enabled: true
    ports:
      http:
        enabled: true
        port: 80
        targetPort: 8080
      metrics:
        enabled: true
        port: 8090
        targetPort: 8090

defaultProbes: &default_probes
  enabled: false
  custom: true
  spec:
    httpGet:
      path: "/"
      port: 8090

probes:
  liveness:
    <<: *default_probes
  readiness:
    <<: *default_probes
  startup:
    <<: *default_probes

initContainers:
  parameter-download:
    image: ubuntu
    command: ["sh", "-c", "/download-params.sh params"]
    volumeMounts:
      - name: verifier
        mountPath: /verifier
      - name: download-params
        mountPath: /download-params.sh
        subPath: download-params.sh
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "8Gi"
        cpu: "2"

configMaps:
  download-params:
    enabled: true
    data:
      download-params.sh: |
        #!/bin/bash

        set -ex

        apt update
        apt install wget libdigest-sha-perl -y
        OPENVM_URL="https://circuit-release.s3.us-west-2.amazonaws.com/scroll-zkvm/releases"
        OPENVM_FILES=("verifier.bin" "root-verifier-vm-config" "root-verifier-committed-exe" "openVmVk.json")
        OPENVM_VERSIONS=("0.4.3" "0.5.2")

        # download files
        download_file_no_checksum() {
          file=$1
          url=$2
          if [ ! -f $file ]; then
            mkdir -p $(dirname $file)
            echo "Downloading $file..."
            wget --progress=dot:giga $url -O $file
            echo "Download completed $file"
          fi
        }

        main(){
          # download openvm-${VERSION} verifier
          for v in "${OPENVM_VERSIONS[@]}";do
            for f in "${OPENVM_FILES[@]}"; do
              download_file_no_checksum "/verifier/openvm-$v/$f" "$OPENVM_URL/$v/verifier/$f"
            done
          done
        }

        main




serviceMonitor:
  main:
    enabled: true
    labels:
      release: scroll-sdk
    serviceName: '{{ include "scroll.common.lib.chart.names.fullname" $ }}'
    endpoints:
      - port: metrics
        interval: 1m
        scrapeTimeout: 10s

ingress:
  main:
    enabled: true
    primary: true
    annotations: {}
    labels: {}
    ingressClassName: "nginx"
    hosts:
      - host: coordinator-api.scrollsdk
        paths:
          - path: /
            pathType: Prefix

scrollConfig: |
  {}
