apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "celestia-node.fullname" . }}-config
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
data:
  config.toml: |
    {{- tpl (.Values.configToml | default "") . | nindent 4 }}
