{{- if .Values.mnemonic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "celestia-node.fullname" . }}-mnemonic
  labels:
    {{- include "celestia-node.labels" . | nindent 4 }}
type: Opaque
data:
  mnemonic: {{ .Values.mnemonic | b64enc }}
{{- end }}