---
global:
  isStandalone: false

image:
  repository: dogeos69/scroll-stack-contracts
  tag: deploy-de732bfee2c6afdebb6a860ab6c79bd8da47832d

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
