---
global:
  isStandalone: false

image:
  repository: dogeos69/scroll-stack-contracts
  tag: deploy-c94e1a901a9e4e98d83828bb1b2eda3c76d42333

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
