---
global:
  isStandalone: false

image:
  repository: dogeos69/scroll-stack-contracts
  tag: deploy-64c65842e35017142b68d878e691dae7e41a7af9

envFrom:
  - configMapRef:
      name: contracts-deployment-env

# here is the place for the config.toml file
scrollConfig: |
  {}

# here is the place for the config-contracts.toml file
scrollConfigContracts: |
  {}
