apiVersion: v2
name: dogecoin
description: Deploy a Dogecoin FullNode in Kubernetes
type: application
version: 0.1.8
appVersion: "1.14.9"
maintainers:
  - name: Dogecoin
    email: support@dogecoin.org

dependencies:
  - name: external-secrets-lib
    repository: "oci://ghcr.io/dogeos69/scroll-sdk/helm"
    version: 0.0.4
