{{- if and .Values.protocolContext (ne (trim .Values.protocolContext) "{}") }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "scroll-common.labels" $ | nindent 4 }}
  name: protocol-context-config
data:
  protocol_context.json: |
{{ .Values.protocolContext | indent 4 }}
{{- end }}
