"""Health policy owned by scroll-monitor, never generated by the CLI.

Internal queries return 0 (healthy), 1 (complete failure), 2 (confirmed failure
with incomplete coverage), or no sample (unknown). Custom queries remain binary.
The runtime also checks the Prometheus envelope. These rules cover public queue latency,
canonical WF progress and configured public probes, not new-work signer quorum
or end-to-end payment. See dogeos-core/docs/engineering/bridge-health-evaluator.md.
"""
import json
import math
from pathlib import Path

# The same progress expression and duration render L2BatchHeightStalled.
L2_PROGRESS = json.loads(Path(__file__).with_name('l2-batch-progress.json').read_text())

DEFAULTS = {
    'withdrawalProcessorExpectedTargets': 1, 'ethDaSubmitterExpectedTargets': 1,
    'tsoExpectedTargets': 1, 'tsoJobRegex': 'tso-service',
    'kubeStateMetricsJobRegex': '.*kube-state-metrics.*',
    'withdrawalProcessorStatefulSet': 'withdrawal-processor',
    'freshnessSeconds': 120, 'failureFor': '5m', 'recoveryFor': '10m',
    'depositDeadlineSeconds': 0, 'withdrawalDeadlineSeconds': 0,
    'batchPublicationDeadlineSeconds': 0, 'wfStallSeconds': 3600,
    'withdrawalProcessorJobRegex': 'withdrawal-processor',
    'ethDaSubmitterJobRegex': 'eth-da-submitter', 'minimumProbeLocations': 2,
    'maxRpcLatencySeconds': 2, 'maxBlockAgeSeconds': 120,
    'maxIndexLagSeconds': 120, 'maxNodeLagSeconds': 120,
}
COMPONENTS = ('public-rpc', 'sequencing', 'deposits', 'withdrawals',
              'batch-publication', 'node-sync', 'bridge-portal', 'block-explorer')


def policy(raw):
    if not isinstance(raw, dict) or raw.keys() - DEFAULTS.keys():
        raise ValueError('unknown health policy field')
    result = {**DEFAULTS, **raw}
    for key, value in result.items():
        if key.endswith('For'):
            seconds(value)
        elif key.endswith(('JobRegex', 'StatefulSet')):
            if not isinstance(value, str) or not value or len(value) > 256:
                raise ValueError('invalid source selector')
        elif (type(value) not in (int, float) or not math.isfinite(value) or value < 0
              or (not key.endswith('DeadlineSeconds') and value == 0)
              or (key != 'maxRpcLatencySeconds' and value != int(value))):
            raise ValueError('invalid health threshold')
    if any(result[key] > 32 for key in ('withdrawalProcessorExpectedTargets', 'ethDaSubmitterExpectedTargets', 'tsoExpectedTargets')):
        raise ValueError('at most 32 expected service targets')
    if result['minimumProbeLocations'] < 2:
        raise ValueError('independent probe locations required')
    return result


def seconds(value):
    if (not isinstance(value, str) or len(value) < 2 or value[-1] not in 'hms'
            or not value[:-1].isdigit() or int(value[:-1]) <= 0):
        raise ValueError('invalid confirmation duration')
    return int(value[:-1]) * {'h': 3600, 'm': 60, 's': 1}[value[-1]]


def quoted(value):
    return json.dumps(str(value))


def fresh(stamp, health):
    return f"(time() - {stamp} >= 0 and time() - {stamp} <= {health['freshnessSeconds']})"


def source(config, key):
    name = 'ethDaSubmitterJobRegex' if key == 'batch-publication' else 'withdrawalProcessorJobRegex'
    return '{namespace=' + quoted(config['sourceNamespace']) + ',job=~' + quoted(config['health'][name]) + '}'


def verdict(value, complete):
    # Keep the independently confirmed fault AND the evidence gap. A partial
    # fault may publish, but must not claim complete monitoring for heartbeat.
    return (f'(({value} == 1) and ({complete})) or (({value} == 1) * 2) '
            f'or (({value} == 0) and ({complete}))')


def queue_query(config, key):
    health = config['health']
    prefix, deadline = {
        'deposits': ('withdrawal_processor_public_deposit', 'depositDeadlineSeconds'),
        'withdrawals': ('withdrawal_processor_public_withdrawal', 'withdrawalDeadlineSeconds'),
        'batch-publication': ('eth_da_publish_public', 'batchPublicationDeadlineSeconds'),
    }[key]
    if health[deadline] == 0:
        return ''  # Unconfigured is unknown, not disabled/healthy.
    selector = source(config, key)
    metric = lambda name: f'{prefix}_{name}{selector}'
    backlog, age, stamp = map(metric, ('eligible_backlog', 'oldest_eligible_age_seconds', 'snapshot_timestamp_seconds'))
    labels = 'namespace, job, instance'
    paired = f'(({backlog} > bool 0) * on ({labels}) ({age} > bool {health[deadline]}))'
    validity = '' if key == 'batch-publication' else f' and on ({labels}) ({metric("snapshot_valid")} == 1)'
    valid = f'({paired} and on ({labels}) ({backlog} >= 0 and {backlog} < Inf and {backlog} == floor({backlog})) and on ({labels}) ({age} >= 0 and {age} < Inf) and on ({labels}) {fresh(stamp, health)}{validity} and on ({labels}) (up{selector} == 1))'
    expected = health["ethDaSubmitterExpectedTargets" if key == "batch-publication" else "withdrawalProcessorExpectedTargets"]
    complete = f'(count({valid}) == count(up{selector})) and (min(up{selector}) == 1) and (count(up{selector}) == {expected})'
    # An independently confirmed fault survives missing evidence elsewhere.
    return verdict(f'max({valid})', complete)


def workflow_query(config):
    health = config['health']
    selector, labels = source(config, 'deposits'), 'namespace, job, instance'
    metric = lambda name: f'withdrawal_processor_public_workflow_{name}{selector}'
    observed, unchanged, head = map(metric, ('snapshot_timestamp_seconds', 'unchanged_seconds', 'head_observed_timestamp_seconds'))
    valid_head = f'({metric("snapshot_valid")} == 1 and on ({labels}) {fresh(observed, health)} and on ({labels}) ({head} > 0 and {head} <= time()) and on ({labels}) ({unchanged} >= 0 and {unchanged} < Inf and {unchanged} <= ({observed} - {head} + 1)) and on ({labels}) (up{selector} == 1))'
    jobs_selector = selector[:-1] + ',source="jobs"}'
    jobs = f'(withdrawal_processor_protocol_snapshot_valid{jobs_selector} == 1 and {fresh("withdrawal_processor_protocol_snapshot_timestamp_seconds" + jobs_selector, health)})'
    age = 'withdrawal_processor_protocol_job_oldest_age_seconds' + selector[:-1] + ',status=~"queued|building|built|failed_retryable|bug|proposed_to_tso|awaiting_replay"}'
    valid_age = f'({age} >= 0 and {age} < Inf and {fresh("timestamp(" + age + ")", health)})'
    waiting, limit = f'(max by ({labels}) ({valid_age}))', health['wfStallSeconds']
    healthy = f'(({waiting} <= bool {limit}) == 1) or on ({labels}) (({waiting} > bool {limit}) * on ({labels}) (time() - {head} <= bool {limit}) == 1)'
    stalled = f'(({waiting} > bool {limit}) * on ({labels}) ({unchanged} > bool {limit}) == 1)'
    state = f'(({stalled}) or on ({labels}) (({healthy}) * 0))'
    evidence = f'({state} and on ({labels}) {valid_head} and on ({labels}) {jobs} and on ({labels}) (count by ({labels}) ({valid_age}) == count by ({labels}) ({age})))'
    expected = health["withdrawalProcessorExpectedTargets"]
    complete = f'(count({evidence}) == count(up{selector})) and (min(up{selector}) == 1) and (count(up{selector}) == {expected})'
    return verdict(f'max({evidence})', complete)


def l2_progress_query(config):
    """AdvanceL1 cannot prove that published L2 batches are being adopted.

    Use the alert's stable namespace/job identity across Pod IP changes. Current
    and window-start evidence must be valid. Gaps inside an otherwise stalled
    window make a confirmed fault partial, never healthy. A new service without
    window-start evidence remains unknown. Rollback is not forward progress.
    """
    h = config['health']
    selector, targets, labels = source(config, 'withdrawals'), 'namespace, job, instance', 'namespace, job'
    window = f'{L2_PROGRESS["windowSeconds"]}s'
    head = 'withdrawal_processor_protocol_state_l2_batch_height' + selector
    latest = 'withdrawal_processor_protocol_latest_da_batch_height' + selector

    def evidence(offset=''):
        suffix = f' offset {offset}' if offset else ''
        now = f'(time() - {L2_PROGRESS["windowSeconds"]})' if offset else 'time()'
        height, da = head + suffix, latest + suffix
        guards = [f'({m} >= 0 and {m} < Inf and {m} == floor({m}))' for m in (height, da)]
        guards.append(f'(up{selector}{suffix} == 1)')
        for origin in ('replay', 'l2'):
            scoped = selector[:-1] + ',source=' + quoted(origin) + '}'
            stamp = 'withdrawal_processor_protocol_snapshot_timestamp_seconds' + scoped + suffix
            guards += [f'(withdrawal_processor_protocol_snapshot_valid{scoped}{suffix} == 1)',
                       f'({now} - {stamp} >= 0 and {now} - {stamp} <= {h["freshnessSeconds"]})']
        return f'({height} and on ({targets}) ' + f' and on ({targets}) '.join(guards) + ')'

    current, past = evidence(), f'max by ({labels}) ({evidence(window)})'
    pending = f'(min by ({labels}) (({latest} > bool on ({targets}) {head}) and on ({targets}) {current}))'
    history = f'({pending})[{window}:1m]'
    progress = (L2_PROGRESS['expr'].replace('__SELECTOR__', head)
                .replace('__LABELS__', labels).replace('__WINDOW__', window))
    # The offset anchor prevents a newly discovered target from claiming the
    # full duration between minute-aligned subquery points.
    stalled = (f'(({progress}) == 0) + 1'
               f' and on ({labels}) (min_over_time({history}) == 1)'
               f' and on ({labels}) {past}'
               f' and on ({labels}) (min by ({labels}) ({latest} offset {window} > bool on ({targets}) {head} offset {window}) == 1)')
    healthy = (f'({pending} == 0) or on ({labels}) (min_over_time({history}) == 0)'
               f' or on ({labels}) ((({progress}) > 0) and on ({labels}) (max by ({labels}) ({current}) > {past}))')
    state = f'((({stalled}) or on ({labels}) (({healthy}) * 0)) and on ({labels}) {current})'
    complete = (f'(count({current}) == count(up{selector})) and (min(up{selector}) == 1)'
                f' and (count(up{selector}) == {h["withdrawalProcessorExpectedTargets"]})'
                f' and ((min(count_over_time({history})) == scalar(count_over_time((vector(1))[{window}:1m]))) or (max({state}) == 0))')
    return verdict(f'max({state})', complete)


def processor_query(config):
    """Supervisor evidence is independent of a failed application scrape.

    Require one current, observed StatefulSet generation from a fresh healthy
    kube-state-metrics target. Missing/duplicate/stale discovery is unknown.
    """
    h = config['health']
    selector = ('{namespace=' + quoted(config['sourceNamespace']) + ',statefulset='
                + quoted(h['withdrawalProcessorStatefulSet']) + ',job=~'
                + quoted(h['kubeStateMetricsJobRegex']) + '}')
    ready = 'kube_statefulset_status_replicas_ready' + selector
    desired = 'kube_statefulset_replicas' + selector
    generation = 'kube_statefulset_metadata_generation' + selector
    observed = 'kube_statefulset_status_observed_generation' + selector
    up = 'up{job=~' + quoted(h['kubeStateMetricsJobRegex']) + '}'
    guards = [f'count({m}) == 1 and {fresh("min(timestamp(" + m + "))", h)}'
              for m in (ready, desired, generation, observed)]
    guards += [f'min({ready}) >= 0 and min({ready}) == floor(min({ready}))',
               f'min({desired}) >= min({ready}) and min({desired}) < Inf',
               f'min({generation}) == min({observed}) and min({generation}) >= 0',
               f'count({ready} and on (job, instance) ({up} == 1)) == 1',
               f'count({up}) == 1 and min({up}) == 1 and {fresh("min(timestamp(" + up + "))", h)}']
    return f'(max({ready}) == bool 0) and (' + ') and ('.join(guards) + ')'


def tso_query(config):
    h = config['health']
    selector = '{namespace=' + quoted(config['sourceNamespace']) + ',job=~' + quoted(h['tsoJobRegex']) + '}'
    ready = 'tso_service_ready' + selector
    valid = 'tso_service_readiness_snapshot_valid' + selector
    stamp = 'tso_service_readiness_timestamp_seconds' + selector
    labels = 'namespace, job, instance'
    evidence = (f'((1 - ({ready} == 0 or {ready} == 1)) and on ({labels}) ({valid} == 1) '
                f'and on ({labels}) {fresh(stamp, h)} and on ({labels}) (up{selector} == 1))')
    complete = f'(count({evidence}) == {h["tsoExpectedTargets"]}) and (count(up{selector}) == {h["tsoExpectedTargets"]}) and (min(up{selector}) == 1)'
    return verdict(f'max({evidence})', complete)


def probe_query(config, key):
    identity = f'environment={quoted(config["environment"])},chain_id={quoted(config["chainId"])},component_key={quoted(key)}'
    health = config['health']
    official = key in ('node-sync', 'sequencing') and config.get('nodeSyncMode') == 'official'
    prefix = ('scroll_status_node_sync' if key == 'node-sync' else 'scroll_status_sequencing') if official else 'scroll_status_probe'
    sample, stamp = (f'{prefix}_{name}{{{identity}}}' for name in ('affected', 'timestamp_seconds'))
    if official:
        valid = f'((({sample} == 0) or ({sample} == 1)) and {fresh(stamp, health)})'
        return f'(max({valid})) and (count({valid}) == 1) and (count({sample}) == 1)'
    valid = f'((({sample} == 0) or ({sample} == 1)) and on (environment, chain_id, component_key, location) {fresh(stamp, health)})'
    count = health['minimumProbeLocations']
    return f'(min({valid})) and (count({valid}) == {count}) and (max({valid}) == min({valid})) and (count(count by (location) ({valid})) == {count})'


def alloy_query(config, key):
    health = config['health']
    alloy = config.get('alloyProbes') or {}
    terms = []
    for target in alloy.get('targets', []) + alloy.get('websocketTargets', []):
        if target['component_key'] != key:
            continue
        websocket = target in alloy.get('websocketTargets', [])
        job = 'status-page-alloy-websocket' if websocket else 'status-page-alloy'
        selector = '{job=' + quoted(job) + ',' + ','.join(f'{label}={quoted(target[label])}' for label in ('environment', 'chain_id', 'component_key', 'check_id', 'status_probe_config')) + '}'
        sample = ('scroll_status_ws_success' if websocket else 'probe_success') + selector
        stamp = 'scroll_status_ws_timestamp_seconds' + selector if websocket else f'timestamp({sample})'
        up = 'up{job="status-page-alloy-websocket"}' if websocket else 'up' + selector
        up_guard = f'on () (min({up}) == 1 and count({up}) == 1)' if websocket else f'({up} == 1) and {fresh("timestamp(" + up + ")", health)}'
        valid = f'(({sample} == 0 or {sample} == 1) and {fresh(stamp, health)} and {up_guard})'
        value = f'(1 - {valid})'
        guard = f'(count({sample}) == 1) and (count({up}) == 1)'
        if key == 'public-rpc':
            duration = ('scroll_status_ws_duration_seconds' if websocket else 'probe_duration_seconds') + selector
            value = f'clamp_max({value} + (quantile_over_time(0.95, {duration}[5m]) > bool {health["maxRpcLatencySeconds"]}), 1)'
            guard += f' and (count({duration}) == 1) and (min(count_over_time({duration}[5m])) >= 10) and (min({duration}) >= 0) and (max({duration}) < Inf) and {fresh("min(timestamp(" + duration + "))", health)}'
        terms.append(f'(max({value}) and {guard})')
    if not terms:
        return ''
    all_targets = f'clamp_max({" + ".join(terms)}, 1)'
    value = '(' + ' or '.join(f'({term} == 1)' for term in terms) + f' or ({all_targets}))'
    return verdict(value, f'count({all_targets}) == 1')


def queries(config, key):
    component = config['components'][key]
    if component.get('mode') == 'manual' or component.get('missing'):
        return {}
    rule = component.get('rule', {})
    if not rule.get('builtin'):
        return {'custom': rule['expr']} if rule.get('expr') else {}
    if key in ('deposits', 'withdrawals'):
        return {'queue_deadline': queue_query(config, key), 'workflow_stalled': workflow_query(config),
                'withdrawal_processor_unready': processor_query(config), 'tso_unready': tso_query(config),
                **({'l2_progress_stalled': l2_progress_query(config)} if key == 'withdrawals' else {})}
    if key == 'batch-publication':
        return {'queue_deadline': queue_query(config, key)}
    if config.get('probeMode') == 'alloy' and key in ('public-rpc', 'bridge-portal', 'block-explorer'):
        return {'probe_failed': alloy_query(config, key)}
    return {'probe_failed': probe_query(config, key)}


def evaluate(samples):
    """Prototype semantics: a fresh known failure wins; recovery needs all facts.

    A failed scrape, absent metric, incomplete signer census or SQL budget expiry
    is not proof of process death. No registered-signer count is used as quorum.
    """
    failed = [rule for rule, value in samples.items() if value in (1, 2)]
    missing = [rule for rule, value in samples.items() if value is None]
    status = ('unavailable' if set(failed) & {'workflow_stalled', 'l2_progress_stalled', 'withdrawal_processor_unready', 'tso_unready'} else 'degraded') if failed else ('operational' if samples and not missing else 'unknown')
    return {'status': status, 'observation': 'partial' if missing or not samples or 2 in samples.values() else 'complete',
            'reasons': failed or missing or ([] if samples else ['unconfigured']),
            'assurance': 'pipeline', 'coverage': 'configured_public_rules'}
