---
{{- include "scroll.common.loader.init" . }}

{{- define "app-template.hardcodedValues" -}}
# Set the nameOverride based on the release name if no override has been set
{{ if not .Values.global.nameOverride }}
global:
  nameOverride: "{{ .Release.Name }}"
{{ end }}
{{- end -}}
{{- $_ := mergeOverwrite .Values (include "app-template.hardcodedValues" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "scroll.common.loader.generate" . }}
---
{{/* Explicitly include the template to render ExternalSecret resources */}}
{{/* This ensures that the .Values.externalSecrets block is processed */}}
{{- include "scrolllib.externalsecrets.tpl" . }}
