apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bridge
  labels:
    app: {{ .Release.Name }}-bridge
spec:
  ports:
    - port: 26658
      targetPort: 26658
      name: rpc
    - port: 2121
      targetPort: 2121
      protocol: TCP
      name: p2p-tcp
    - port: 2121
      targetPort: 2121
      protocol: UDP
      name: p2p-udp
  selector:
    app: {{ .Release.Name }}-bridge
