apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-validator
  labels:
    app: {{ .Release.Name }}-validator
spec:
  ports:
    - port: 26657
      targetPort: 26657
      name: rpc
    - port: 9090
      targetPort: 9090
      name: grpc
    - port: 26656
      targetPort: 26656
      name: p2p
  clusterIP: None
  selector:
    app: {{ .Release.Name }}-validator
