---
apiVersion: v2
name: scroll-monitor-agent
description: Grafana Alloy collectors for Scroll SDK logs and OTLP metrics
type: application
version: 0.1.0-dogeos
appVersion: v1.8.2
kubeVersion: ">=1.22.0-0"
maintainers:
  - name: scroll-tech
    email: sebastien@scroll.io
dependencies:
  - name: alloy
    repository: "https://grafana.github.io/helm-charts"
    version: 1.0.2
    condition: enabled
