{
 "title": "Scroll Rollup Node",
 "description": "Adapted for Kubernetes from scroll-tech/rollup-node v1.0.7-rc6 (bc3d5006c41b38cc442ebe92d1afc4285fc43ca1) (docker-compose/resource/dashboards/rollup_node.json). Select one namespace, service, and pod for drill-down. Upstream source: https://github.com/scroll-tech/rollup-node/tree/v1.0.7-rc6/docker-compose/resource/dashboards",
 "tags": [
  "reth",
  "scroll",
  "l2",
  "service",
  "upstream-dashboard"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(reth_info, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(reth_info{namespace=~\"$namespace\",service=~\"l2-reth-(sequencer|bootnode)-[0-9]+|l2-reth-rpc(-public)?|l2-rpc\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(reth_info{namespace=~\"$namespace\",service=~\"$service\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync height",
   "type": "bargauge",
   "description": "Canonical chain height for the selected Scroll L2 Reth pod.",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_blockchain_tree_canonical_chain_height{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Block building",
   "type": "timeseries",
   "description": "Metrics related to block building.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_chain_orchestrator_block_building_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=\"1.0\"}",
     "legendFormat": "Block building duration"
    }
   ]
  },
  {
   "title": "Payload attributes building duration",
   "type": "timeseries",
   "description": "The duration for the sequencer to assemble the payload attributes for the block. This should not include the payload building duration allocated to the EN.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_sequencer_payload_attributes_building_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=~\"0.5|0.95|1.0\"}",
     "legendFormat": "Payload building duration - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Chain orchestrator task handling duration",
   "type": "timeseries",
   "description": "The average duration for tasks handled by the chain orchestrator.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_chain_orchestrator_task_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=~\"0.5|0.95|0.99\"}",
     "legendFormat": "{{task}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Signing duration",
   "type": "timeseries",
   "description": "The duration of the signing task for the Signer component.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_signer_signing_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=~\"0.5|0.95|1.0\"}",
     "legendFormat": "Duration p{{quantile}} "
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Database write operations",
   "type": "timeseries",
   "description": "Duration of database read operations.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_database_task_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=\"0.99\",item!~\".*(?i)get.*\"}",
     "legendFormat": "{{item}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Database read operations",
   "type": "timeseries",
   "description": "Duration of database read operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "reth_database_task_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=\"0.99\",item=~\".*(?i)get.*\"}",
     "legendFormat": "{{item}} - p{{quantile}}"
    }
   ]
  },
  {
   "title": "Locks acquisition duration",
   "type": "timeseries",
   "description": "The duration for the database to acquire read and write locks.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "reth_database_read_lock_acquire_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=~\"0.5|0.9|1.0\"}",
     "legendFormat": "Read lock acquisition - p{{quantile}}"
    },
    {
     "expr": "reth_database_write_lock_acquire_duration{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",quantile=~\"0.5|0.9|1.0\"}",
     "legendFormat": "Write lock acquisition - p{{quantile}}"
    }
   ]
  },
  { "title": "Derivation pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Derived L2 payload attributes",
   "type": "timeseries",
   "description": "L2 attributes derived from the L1 by the derivation pipeline.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "attributes" } },
   "targets": [
    {
     "expr": "reth_derivation_pipeline_derived_blocks{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "attributes"
    },
    {
     "expr": "reth_derivation_pipeline_blocks_per_second{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "attributes/second"
    }
   ]
  },
  {
   "title": "Derivation queue sizes",
   "type": "timeseries",
   "description": "Live sizes of the derivation pipeline queues.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "items" } },
   "targets": [
    {
     "expr": "reth_derivation_pipeline_batch_queue_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "batch_queue_size"
    },
    {
     "expr": "reth_derivation_pipeline_payload_attributes_queue_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "attributes_queue_size"
    }
   ]
  },
  { "title": "L1 watcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Reorg depths",
   "type": "histogram",
   "description": "A histogram of the L1 reorg depths.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "reth_l1_watcher_reorg_depths{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Reorg depth"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "timeseries",
   "description": "The current sync status of the L1 watcher.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "reth_l1_watcher_l1_messages{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Indexed L1 messages"
    },
    {
     "expr": "reth_l1_watcher_batch_commits{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Indexed batch commits"
    },
    {
     "expr": "reth_l1_watcher_batch_finalizations{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Indexed batch finalizations"
    }
   ]
  },
  {
   "title": "Reorgs",
   "type": "timeseries",
   "description": "The L1 reorg count.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "reth_l1_watcher_reorgs{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "Reorgs"
    }
   ]
  }
 ]
}