{
 "title": "Scroll L2 Reth State & History",
 "description": "Adapted for Kubernetes from scroll-tech/rollup-node v1.0.7-rc6 (bc3d5006c41b38cc442ebe92d1afc4285fc43ca1) (docker-compose/resource/dashboards/state_history.json). Select one namespace, service, and pod for drill-down. Upstream source: https://github.com/scroll-tech/rollup-node/tree/v1.0.7-rc6/docker-compose/resource/dashboards",
 "tags": [
  "reth",
  "scroll",
  "l2",
  "service",
  "upstream-dashboard"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(reth_info, namespace)"
    }
   },
   {
    "name": "service",
    "query": {
     "query": "label_values(reth_info{namespace=~\"$namespace\",service=~\"l2-reth-(sequencer|bootnode)-[0-9]+|l2-reth-rpc(-public)?|l2-rpc\"}, service)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(reth_info{namespace=~\"$namespace\",service=~\"$service\"}, pod)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Build Timestamp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{build_timestamp}}"
    }
   ]
  },
  {
   "title": "Git SHA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{git_sha}}"
    }
   ]
  },
  {
   "title": "Build Profile",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{build_profile}}"
    }
   ]
  },
  {
   "title": "Target Triple",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{target_triple}}"
    }
   ]
  },
  {
   "title": "Cargo Features",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "reth_info{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{cargo_features}}"
    }
   ]
  },
  { "title": "State", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "State Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainAccountState\"}[$interval]))",
     "legendFormat": "Account"
    },
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainStorageState\"}[$interval]))",
     "legendFormat": "Storage"
    },
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Bytecodes\"}[$interval]))",
     "legendFormat": "Bytecodes"
    },
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainAccountState\"}[$interval])) + avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainStorageState\"}[$interval])) + avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Bytecodes\"}[$interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "State Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainAccountState\"})",
     "legendFormat": "Account"
    },
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainStorageState\"})",
     "legendFormat": "Storage"
    },
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Bytecodes\"})",
     "legendFormat": "Bytecodes"
    },
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=~\"PlainAccountState|PlainStorageState|Bytecodes\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Account State Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainAccountState\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage State Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"PlainStorageState\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bytecodes Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Bytecodes\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "History Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Headers\"}[$interval])) + avg(delta(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"headers\"}[$interval]))",
     "legendFormat": "Headers"
    },
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Receipts\"}[$interval])) + avg(delta(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"receipts\"}[$interval]))",
     "legendFormat": "Receipts"
    },
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Transactions\"}[$interval])) + avg(delta(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"transactions\"}[$interval]))",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "History Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Headers\"}) + sum(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"headers\"})",
     "legendFormat": "Headers"
    },
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Receipts\"}) + sum(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"receipts\"})",
     "legendFormat": "Receipts"
    },
    {
     "expr": "sum(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Transactions\"}) + sum(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"transactions\"})",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Headers Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Headers\"}[$interval])) + avg(delta(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"headers\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Receipts Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Receipts\"}[$interval])) + avg(delta(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"receipts\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transactions Growth (interval = ${interval})",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(delta(reth_db_table_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",table=\"Transactions\"}[$interval])) + avg(delta(reth_static_files_segment_size{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\",segment=\"transactions\"}[$interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}