{
 "title": "Celestia",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "das_total_sampled_headers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "das_total_sampled_headers{}", "legendFormat": "total sampled" }
   ]
  },
  {
   "title": "das_sampled_chain_head",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "das_sampled_chain_head{}", "legendFormat": "chain head" }
   ]
  },
  {
   "title": "das_sampled_headers_counter_total (overall per-second rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(das_sampled_headers_counter_total{}[$__rate_interval]))",
     "legendFormat": "headers counter total"
    }
   ]
  },
  {
   "title": "das_sample_time_hist_bucket",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(das_sample_time_hist_bucket{}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(das_sample_time_hist_bucket{}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(das_sample_time_hist_bucket{}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  }
 ]
}