# # config file version
apiVersion: 1
# List of rule groups to import or update
groups:
    - orgId: 1
      name: dogeos alert provisioned
      folder: dogeos
      interval: 1m
      rules:
        - uid: eemuhs8xgrjlsf
          title: Error Json Log Alert(Paused)
          condition: B
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P8E80F9AEF21F6940
              model:
                datasource:
                    type: loki
                    uid: P8E80F9AEF21F6940
                editorMode: code
                expr: sum by (service, level, message)(count_over_time({service=~".*(dogeos-deposit-processor|cubesigner).*", level=~"(?i)warn|error"} | pattern "<_>{<message>}"[10m]))
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: 'Occurrences: {{ $values.A.Value }}'
          labels: {}
          isPaused: true
          notification_settings:
            receiver: dogeos default slack alert
            repeat_interval: 5m
        - uid: een2zs3umqscga
          title: Error Log Alert(Paused)
          condition: B
          data:
            - refId: A
              queryType: instant
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: P8E80F9AEF21F6940
              model:
                datasource:
                    type: loki
                    uid: P8E80F9AEF21F6940
                editorMode: code
                expr: sum by (service, level, message)(count_over_time({service=~"(dogeos-da)|(withdrawal-processor)|(tso-service)"} | decolorize | detected_level=~`warn|error` | regexp ".*?(?P<level>(WARN|ERROR)).*? (?P<message>.*)"[10m]))
                intervalMs: 1000
                maxDataPoints: 43200
                queryType: instant
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: B
                type: threshold
          noDataState: OK
          execErrState: Error
          for: 0s
          annotations:
            summary: 'Occurrences: {{ $values.A.Value }}'
          labels: {}
          isPaused: true
          notification_settings:
            receiver: dogeos default slack alert
            repeat_interval: 5m
        - uid: den31ekvqabr4a
          title: Low Indexing Height(Paused)
          condition: D
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                editorMode: code
                exemplar: false
                expr: sum by(service) (label_replace(dogecoin_synced_headers_total, "service", "dogeos-deposit-processor", "", ""))
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: B
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: PBFA97CFB590B2093
              model:
                datasource:
                    type: prometheus
                    uid: PBFA97CFB590B2093
                editorMode: code
                expr: sum by(service) (dogeos_deposit_processor_current_indexer_height)
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: B
            - refId: D
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: C
                intervalMs: 1000
                maxDataPoints: 43200
                refId: D
                type: threshold
            - refId: C
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0
                            - 0
                        type: gt
                      operator:
                        type: and
                      query:
                        params: []
                      reducer:
                        params: []
                        type: avg
                      type: query
                datasource:
                    name: Expression
                    type: __expr__
                    uid: __expr__
                expression: $A-$B
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: math
          noDataState: NoData
          execErrState: Error
          for: 0s
          annotations:
            summary: |-
                Dogecoin height:  {{ printf "%.0f" $values.A.Value }}
                DogeOS indexer height:  {{ printf "%.0f" $values.B.Value }}
                Difference: {{ printf "%.0f" $values.C.Value }}
          labels: {}
          isPaused: true
          notification_settings:
            receiver: dogeos default slack alert
            repeat_interval: 5m

# List of contact points to import or update
contactPoints:
    - orgId: 1
      name: dogeos default slack alert
      receivers:
        - uid: demuhr48nt3wgf
          type: slack
          settings:
            text: '{{ template "slack.dogeos.text" . }}'
            title: '{{ template "slack.dogeos.title" . }}'
            url: https://hooks.slack.com/services/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
          disableResolveMessage: false

# List of templates to import or update
templates:
    # <int> organization ID, default = 1
  - orgID: 1
    # <string, required> name of the template, must be unique
    name: template.dogeos.provisioned
    # <string, required> content of the template
    template: "{{ define \"slack.dogeos.title\" }}\n[{{ if eq .Status \"firing\" }}🔥{{ end }}{{ if eq .Status \"resolved\" }}✅{{ end }}{{ .Status | toUpper }}{{ if eq .Status \"firing\" }}:{{ .Alerts.Firing | len }}{{ if gt (.Alerts.Resolved | len) 0 }}, ✅RESOLVED{{ end }}{{ end }}{{ if gt (.Alerts.Resolved | len) 0 }}:{{ .Alerts.Resolved | len }}{{ end }}] {{ .GroupLabels.alertname }} in {{ with .CommonLabels.service }}{{ . }}{{ else }}multiple services{{ end }}\n{{ end }}\n\n\n{{ define \"slack.dogeos.text\" }}\nHere are details:\n{{ if gt (len .Alerts.Firing) 0 }}🔥🔥🔥 {{ len .Alerts.Firing }} FIRING 🔥🔥🔥\n{{ template \"dogeos_text_alert_list\" .Alerts.Firing }}{{ if gt (len .Alerts.Resolved) 0 }}\n{{ end }}{{ end }}{{ if gt (len .Alerts.Resolved) 0 }}✅✅✅ {{ len .Alerts.Resolved }} RESOLVED ✅✅✅\n{{ template \"dogeos_text_alert_list\" .Alerts.Resolved }}{{ end }}{{ end }}\n\n\n{{ define \"dogeos_text_alert_list\" }}{{ range . }}\nLabels:\n{{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}\n{{ end }}Annotations:\n{{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}\n{{ end }}{{ if gt (len .GeneratorURL) 0 }}Source: {{ .GeneratorURL }}\n{{ end }}{{ if gt (len .SilenceURL) 0 }}Silence: {{ .SilenceURL }}\n{{ end }}{{ if gt (len .DashboardURL) 0 }}Dashboard: {{ .DashboardURL }}\n{{ end }}{{ if gt (len .PanelURL) 0 }}Panel: {{ .PanelURL }}\n{{ end }}{{ end }}{{ end }}"

