NAMESPACE ?= default

.PHONY: prepare install-dogecoin install-celestia install-l1-devnet install-scroll-core \
	install-l2-sequencer install-l2-bootnode install-contracts install-dogeos-da \
	install-rollup-node install-gas-oracle install-deposit-processor \
	install-cubesigner-signers install-tso install-withdrawal-processor \
	install-blockscout install-frontends install-testnet-activity-helper install-all \
	delete-all delete-l1-devnet delete-dogecoin delete-celestia delete-frontends \
	delete-blockscout delete-withdrawal-processor delete-deposit-processor delete-tso \
	delete-dogeos-da delete-gas-oracle delete-rollup-node delete-cubesigner-signers \
	delete-testnet-activity-helper

prepare:
	helm repo add grafana https://grafana.github.io/helm-charts
	helm repo update

install-dogecoin:
	helm upgrade -i dogecoin-testnet oci://ghcr.io/dogeos69/scroll-sdk/helm/dogecoin -n $(NAMESPACE) \
		--version=0.1.4 \
		--values values/dogecoin-production.yaml

install-celestia:
	helm upgrade -i celestia-testnet oci://ghcr.io/dogeos69/scroll-sdk/helm/celestia-node -n $(NAMESPACE) \
		--version=0.1.5 \
		--values values/celestia-node-production.yaml

install-l1-devnet:
	helm upgrade -i l1-devnet oci://ghcr.io/dogeos69/scroll-sdk/helm/l1-devnet -n $(NAMESPACE) \
		--wait  \
		--version=0.1.4 \
		--values values/l1-devnet-production.yaml

install-scroll-core:
	helm upgrade -i scroll-monitor oci://ghcr.io/dogeos69/scroll-sdk/helm/scroll-monitor -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/scroll-monitor-production.yaml

	helm upgrade -i scroll-common oci://ghcr.io/dogeos69/scroll-sdk/helm/scroll-common -n $(NAMESPACE) \
		--version=0.1.1-dogeos \
		--values values/genesis.yaml

	helm upgrade -i grafana-alloy grafana/alloy -n $(NAMESPACE) \
		--version=1.0.2 \
		--values values/grafana-alloy-production.yaml

	helm upgrade -i metrics-exporter oci://ghcr.io/dogeos69/scroll-sdk/helm/metrics-exporter -n $(NAMESPACE) \
		--version=0.1.6 \
		--values values/metrics-exporter-production.yaml

	$(MAKE) install-l2-sequencer

	$(MAKE) install-l2-bootnode


	helm upgrade -i l2-rpc oci://ghcr.io/dogeos69/scroll-sdk/helm/l2-rpc -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/l2-rpc-production.yaml

install-l2-sequencer:
	helm upgrade -i l2-sequencer-0 oci://ghcr.io/dogeos69/scroll-sdk/helm/l2-sequencer -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/l2-sequencer-production-0.yaml

	helm upgrade -i l2-sequencer-1 oci://ghcr.io/dogeos69/scroll-sdk/helm/l2-sequencer -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/l2-sequencer-production-1.yaml

install-l2-bootnode:
	helm upgrade -i l2-bootnode-0 oci://ghcr.io/dogeos69/scroll-sdk/helm/l2-bootnode -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/l2-bootnode-production-0.yaml

	helm upgrade -i l2-bootnode-1 oci://ghcr.io/dogeos69/scroll-sdk/helm/l2-bootnode -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/l2-bootnode-production-1.yaml

install-contracts:
	helm upgrade -i contracts oci://ghcr.io/dogeos69/scroll-sdk/helm/contracts -n $(NAMESPACE) \
		--version=0.1.12 \
		--values values/contracts-production.yaml \
		--values values/scroll-common-config-contracts.yaml \
		--values values/scroll-common-config.yaml
	kubectl wait --for=jsonpath='{.status.phase}'=Succeeded --timeout=360s pod -l app.kubernetes.io/instance=contracts -n $(NAMESPACE)

install-dogeos-da:
	helm upgrade -i dogeos-da oci://ghcr.io/dogeos69/scroll-sdk/helm/dogeos-da -n $(NAMESPACE) \
		--wait  \
		--set image.tag="062625-00" \
		--set image.repository="dogeos69/da-publisher" \
		--version=0.1.2 \
		--values values/dogeos-da-production.yaml

install-rollup-node:
	helm upgrade -i rollup-node oci://ghcr.io/dogeos69/scroll-sdk/helm/rollup-node -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--set image.tag=latest \
		--set image.repository=dogeos69/rollup-relayer \
		--set image.pullPolicy=Always \
		--values values/rollup-node-production.yaml \
		--values values/rollup-node-config.yaml

	helm upgrade -i rollup-explorer-backend oci://ghcr.io/dogeos69/scroll-sdk/helm/rollup-explorer-backend -n $(NAMESPACE) \
		--version=0.1.3-dogeos \
		--values values/rollup-explorer-backend-production.yaml

install-gas-oracle:
	helm upgrade -i gas-oracle oci://ghcr.io/dogeos69/scroll-sdk/helm/gas-oracle -n $(NAMESPACE) \
		--version=0.1.5-dogeos \
		--values values/gas-oracle-production.yaml \
		--values values/gas-oracle-config.yaml

install-deposit-processor:
	helm upgrade -i dogeos-deposit-processor oci://ghcr.io/dogeos69/scroll-sdk/helm/dogeos-deposit-processor -n $(NAMESPACE) \
		--set image.tag=060925-00 \
		--version=0.1.4 \
		--values values/dogeos-deposit-processor-production.yaml

install-cubesigner-signers:
	helm upgrade -i cubesigner-signer-0 oci://ghcr.io/dogeos69/scroll-sdk/helm/cubesigner-signer -n $(NAMESPACE) \
	 	--version=0.1.3 \
		--set image.tag=060925-00 \
		--set image.pullPolicy=Always \
		--values values/cubesigner-signer-production-0.yaml
	helm upgrade -i cubesigner-signer-1 oci://ghcr.io/dogeos69/scroll-sdk/helm/cubesigner-signer -n $(NAMESPACE) \
		--version=0.1.3 \
		--set image.tag=060925-00 \
		--set image.pullPolicy=Always \
		--values values/cubesigner-signer-production-1.yaml
	helm upgrade -i cubesigner-signer-2 oci://ghcr.io/dogeos69/scroll-sdk/helm/cubesigner-signer -n $(NAMESPACE) \
		--version=0.1.3 \
		--set image.tag=060925-00 \
		--set image.pullPolicy=Always \
		--values values/cubesigner-signer-production-2.yaml

install-tso:
	helm upgrade -i tso-service oci://ghcr.io/dogeos69/scroll-sdk/helm/tso-service -n $(NAMESPACE) \
		--version=0.1.0 \
		--set image.tag=v0.1.0-beta \
		--values values/tso-service-production.yaml

install-withdrawal-processor:
	helm upgrade -i withdrawal-processor oci://ghcr.io/dogeos69/scroll-sdk/helm/withdrawal-processor -n $(NAMESPACE) \
		--version=0.1.5 \
		--set image.tag=061125-00 \
		--values values/withdrawal-processor-production.yaml

install-blockscout:
	helm upgrade -i blockscout oci://ghcr.io/dogeos69/scroll-sdk/helm/blockscout -n $(NAMESPACE) \
		--version=0.1.7-dogeos \
		--values values/blockscout-production.yaml

	helm upgrade -i blockscout-sc-verifier oci://ghcr.io/dogeos69/scroll-sdk/helm/blockscout-sc-verifier -n $(NAMESPACE) \
	 	--version=0.1.3-dogeos

install-frontends:
	helm upgrade -i frontends oci://ghcr.io/dogeos69/scroll-sdk/helm/frontends -n $(NAMESPACE) \
		--version=0.1.2-dogeos \
		--values values/frontends-production.yaml \
		--values values/frontends-config.yaml


install-testnet-activity-helper:
	helm upgrade -i testnet-activity-helper oci://ghcr.io/dogeos69/scroll-sdk/helm/testnet-activity-helper -n $(NAMESPACE) \
		--version=0.1.0 \
		--values values/testnet-activity-helper-production.yaml

install-all:
	$(MAKE) install-dogecoin
	$(MAKE) install-celestia
	$(MAKE) install-dogeos-da 
	$(MAKE) install-l1-devnet 
	$(MAKE) install-scroll-core
	kubectl wait --for=condition=Ready --timeout=360s pod -l app.kubernetes.io/instance=l1-devnet -n $(NAMESPACE)
	scrollsdk helper fund-accounts -i -f 2 -d
	scrollsdk helper fund-accounts -l 1 -f 2 -d
	$(MAKE) install-contracts
	scrollsdk helper fund-accounts -l 2 -f 0.2 -d
	$(MAKE) install-rollup-node
	$(MAKE) install-gas-oracle
	$(MAKE) install-deposit-processor
	$(MAKE) install-cubesigner-signers
	$(MAKE) install-tso
	$(MAKE) install-withdrawal-processor
	$(MAKE) install-blockscout
	$(MAKE) install-frontends
	$(MAKE) install-testnet-activity-helper

delete-all:
	helm delete -n $(NAMESPACE) scroll-common || true
	$(MAKE) delete-l2-sequencer  || true
	helm delete -n $(NAMESPACE) frontends || true
	helm delete -n $(NAMESPACE) gas-oracle || true
	helm delete -n $(NAMESPACE) l2-bootnode-0 || true
	helm delete -n $(NAMESPACE) l2-bootnode-1 || true
	helm delete -n $(NAMESPACE) l2-rpc || true
	helm delete -n $(NAMESPACE) rollup-explorer-backend || true
	helm delete -n $(NAMESPACE) rollup-node || true
	helm delete -n $(NAMESPACE) contracts || true
	helm delete -n $(NAMESPACE) scroll-monitor || true
	helm delete -n $(NAMESPACE) metrics-exporter || true
	helm delete -n $(NAMESPACE) grafana-alloy || true
	helm delete -n $(NAMESPACE) blockscout || true
	helm delete -n $(NAMESPACE) blockscout-sc-verifier || true
	helm delete -n $(NAMESPACE) withdrawal-processor || true
	helm delete -n $(NAMESPACE) tso-service || true
	$(MAKE) delete-cubesigner-signers || true
	helm delete -n $(NAMESPACE) dogeos-deposit-processor || true
	helm delete -n $(NAMESPACE) dogeos-da || true
	helm delete -n $(NAMESPACE) l1-devnet || true
	$(MAKE) delete-testnet-activity-helper || true

delete-l1-devnet:
	helm delete -n $(NAMESPACE) l1-devnet

delete-dogecoin:
	helm delete -n $(NAMESPACE) dogecoin-testnet

delete-celestia:
	helm delete -n $(NAMESPACE) celestia-testnet

delete-frontends:
	helm delete -n $(NAMESPACE) frontends

delete-blockscout:
	helm delete -n $(NAMESPACE) blockscout || true
	helm delete -n $(NAMESPACE) blockscout-sc-verifier || true

delete-withdrawal-processor:
	helm delete -n $(NAMESPACE) withdrawal-processor

delete-deposit-processor:
	helm delete -n $(NAMESPACE) dogeos-deposit-processor

delete-tso:
	helm delete -n $(NAMESPACE) tso-service

delete-dogeos-da:
	helm delete -n $(NAMESPACE) dogeos-da

delete-gas-oracle:
	helm delete -n $(NAMESPACE) gas-oracle

delete-rollup-node:
	helm delete -n $(NAMESPACE) rollup-node || true
	helm delete -n $(NAMESPACE) rollup-explorer-backend || true

delete-cubesigner-signers:
	helm delete -n $(NAMESPACE) cubesigner-signer-0 || true
	helm delete -n $(NAMESPACE) cubesigner-signer-1 || true
	helm delete -n $(NAMESPACE) cubesigner-signer-2 || true
	-kubectl delete pvc session-cache-0-cubesigner-signer-0-0
	-kubectl delete pvc session-cache-1-cubesigner-signer-1-0
	-kubectl delete pvc session-cache-2-cubesigner-signer-2-0

delete-testnet-activity-helper:
	helm delete -n $(NAMESPACE) testnet-activity-helper

delete-l2-bootnode:
	helm delete -n $(NAMESPACE) l2-bootnode-0 || true
	helm delete -n $(NAMESPACE) l2-bootnode-1 || true

delete-l2-sequencer:
	helm delete -n $(NAMESPACE) l2-sequencer-0 || true
	helm delete -n $(NAMESPACE) l2-sequencer-1 || true
