{{- if .Values.externalSecrets }}
{{- range $name, $config := .Values.externalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ $name }}
  labels:
    {{- include "testnet-activity-helper.labels" $ | nindent 4 }}
spec:
  provider:
    {{- if eq $config.provider "aws" }}
    aws:
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $config.serviceAccount }}
      region: {{ $config.region | default "us-west-2" }}
      service: SecretsManager
    {{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $name }}
  labels:
    {{- include "testnet-activity-helper.labels" $ | nindent 4 }}
spec:
  data:
    {{- toYaml $config.data | nindent 4 }}
  refreshInterval: {{ $config.refreshInterval | default "5m" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ $name }}
  target:
    creationPolicy: {{ $config.creationPolicy | default "Owner" }}
    deletionPolicy: {{ $config.deletionPolicy | default "Retain" }}
    name: {{ $name }}
{{- end }}
{{- end }} 