{{- if not .Values.externalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testnet-activity-helper.fullname" . }}
  labels:
    {{- include "testnet-activity-helper.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.toml: |
    [accounts]
    DEPLOYER_PRIVATE_KEY = "{{ .Values.config.deployerPrivateKey | default "" }}"
    
    [frontend]
    EXTERNAL_RPC_URI_L2 = "{{ .Values.config.externalRpcUriL2 }}"
{{- end }} 