{{- if not .Values.externalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blockbook.fullname" . }}-rpc-secret
  labels:
    {{- include "blockbook.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.rpcPassword.secretKey }}: {{ .Values.rpcPassword.value | b64enc }}
{{- end }}
