apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockbook.fullname" . }}
  labels:
    {{- include "blockbook.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.publicPort }}
      targetPort: public
      protocol: TCP
      name: public
    - port: {{ .Values.service.internalPort }}
      targetPort: internal
      protocol: TCP
      name: internal
  selector:
    {{- include "blockbook.selectorLabels" . | nindent 4 }}
