envFrom:
  - secretRef:
      name: gas-oracle-secret-env

configMaps:
  env:
    enabled: true
    data:
      SCROLL_L1_RPC: ""
      SCROLL_L2_RPC: ""

externalSecrets:
  gas-oracle-secret-env:
    provider: aws
    data:
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_DB_CONFIG_DSN
        secretKey: SCROLL_ROLLUP_DB_CONFIG_DSN
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_L1_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L1_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
      - remoteRef:
          key: scroll/gas-oracle-secret-env
          property: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
        secretKey: SCROLL_ROLLUP_L2_CONFIG_RELAYER_CONFIG_GAS_ORACLE_SENDER_SIGNER_CONFIG_PRIVATE_KEY_SIGNER_CONFIG_PRIVATE_KEY
    refreshInterval: 2m
    serviceAccount: external-secrets

