{
 "title": "Elli",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(elli_up, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[30s])) without (kind) * 100"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_microseconds_sum{instance=\"$node\"}[30s]))/sum(rate(http_request_duration_microseconds_count{instance=\"$node\"}[30s]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(http_requests_total{instance=\"$node\"}[30s])) + sum(irate(http_requests_failed_total{instance=\"$node\"}[30s]))"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"informational\"}[5m]))/sum(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"informational\"}[5m]))",
     "legendFormat": "1xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"success\"}[5m]))/sum(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"success\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"redirection\"}[5m]))/sum(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"redirection\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"client-error\"}[5m]))/sum(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"client-error\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"server-error\"}[5m]))/sum(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"server-error\"}[5m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum(irate(http_request_duration_microseconds_sum{instance=\"$node\", status_class=\"unknown\"}[5m]))/sum(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"unknown\"}[5m]))",
     "legendFormat": "unknown"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"informational\"}[1m]))"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"success\"}[1m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"redirection\"}[1m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"client-error\"}[1m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"server-error\"}[1m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "sum by (status_class)(irate(http_request_duration_microseconds_count{instance=\"$node\", status_class=\"unknown\"}[1m]))",
     "legendFormat": "unknown"
    },
    {
     "expr": "sum by (reason)(irate(http_requests_failed_total{instance=\"$node\", reason=\"request_closed\"}[1m]))",
     "legendFormat": "closed"
    },
    {
     "expr": "sum by (reason)(irate(http_requests_failed_total{instance=\"$node\", reason=\"timeout\"}[1m]))",
     "legendFormat": "timeout"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "erlang_vm_process_count{instance=\"$node\"}",
     "legendFormat": "Processes"
    },
    {
     "expr": "erlang_vm_statistics_run_queues_length_total{instance=\"$node\"}",
     "legendFormat": "Run Queues Length"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_context_switches{instance=\"$node\"}[5m])",
     "legendFormat": "Context Switches"
    },
    {
     "expr": "irate(erlang_vm_statistics_reductions_total{instance=\"$node\"}[5m])",
     "legendFormat": "Reductions"
    }
   ]
  },
  {
   "title": "VM IO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_bytes_output_total{instance=\"$node\"}[5m])",
     "legendFormat": "Output Bytes"
    },
    {
     "expr": "irate(erlang_vm_statistics_bytes_received_total{instance=\"$node\"}[5m])",
     "legendFormat": "Received Bytes"
    }
   ]
  },
  {
   "title": "VM GC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_number_of_gcs{instance=\"$node\"}[5m])",
     "legendFormat": "Number of GCs"
    },
    {
     "expr": "irate(erlang_vm_statistics_garbage_collection_bytes_reclaimed{instance=\"$node\"}[5m])",
     "legendFormat": "Bytes Reclaimed"
    }
   ]
  },
  {
   "title": "VM Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "erlang_vm_memory_bytes_total{instance=\"$node\", kind=\"processes\"}",
     "legendFormat": "Processes Memory"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"atom\"}",
     "legendFormat": "Atoms"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"binary\"}",
     "legendFormat": "Binary"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"code\"}",
     "legendFormat": "Code"
    },
    {
     "expr": "erlang_vm_memory_system_bytes_total{instance=\"$node\", usage=\"ets\"}",
     "legendFormat": "ETS"
    }
   ]
  },
  {
   "title": "OS Process Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"$node\"}",
     "legendFormat": "Vertual Memory"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"$node\"}",
     "legendFormat": "Resident Memory"
    }
   ]
  },
  {
   "title": "File Descriptors & Ports",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$node\"}",
     "legendFormat": "Open FDs"
    },
    {
     "expr": "process_max_fds{instance=\"$node\"}",
     "legendFormat": "Max FDs"
    },
    {
     "expr": "erlang_vm_port_limit{instance=\"$node\"}",
     "legendFormat": "Max Ports"
    },
    {
     "expr": "erlang_vm_port_count{instance=\"$node\"}",
     "legendFormat": "Ports"
    }
   ]
  },
  {
   "title": "Native Threads & CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_threads_total{instance=\"$node\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "sum(irate(process_cpu_seconds_total{instance=\"$node\"}[30s])) without (kind) * 100",
     "legendFormat": "CPU"
    }
   ]
  }
 ]
}