metricsConfig:
  l1Network:
    url: "http://l1-devnet:8545"
    L1_MESSAGE_QUEUE_PROXY_ADDR: ""
  dogecoin:
    url: "http://dogecoin-testnet:44555"

# External Secrets configuration
externalSecrets:
  metrics-exporter-secrets:
    provider: aws
    data:
      - remoteRef:
          key: scroll/metrics-exporter-secret-env
          property: METRICS_EXPORTER_DOGECOIN_BASIC_AUTH
        secretKey: DOGECOIN_RPC_TOKEN
    refreshInterval: 2m
    serviceAccount: external-secrets