---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "l1-devnet.jwtSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "l1-devnet.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt.hex: "{{ .Values.jwtSecret | trimPrefix "0x" }}"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "l1-devnet.genesisPvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "l1-devnet.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.genesis.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "l1-devnet.gethPvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "l1-devnet.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.geth.storage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "l1-devnet.lighthousePvcName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "l1-devnet.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: {{ .Values.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.lighthouse.storage }}
