apiVersion: v2
name: prover-worker
description: A Helm chart for a compiler-selected DogeOS prover Worker
type: application
version: 0.1.0
appVersion: "0.1.0"
kubeVersion: ">=1.22.0-0"
home: https://github.com/DogeOS69/dogeos-core
sources:
  - https://github.com/DogeOS69/dogeos-core/tree/develop/crates/prover_worker
keywords:
  - dogeos
  - scroll
  - prover-worker
  - zk
maintainers:
  - name: DogeOS69
    email: support@dogeos.com
