{{- if not .Values.externalSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dogecoin.fullname" . }}-rpc-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{ .Values.rpcPassword.secretKey }}: {{ .Values.rpcPassword.value | b64enc | quote }}
{{- end }}
